name: e2e-tests-on-PR
on:
  pull_request:
    branches:
      - '**'
      - '!master'
concurrency:
  group: js-wallet-e2e-tests-${{github.event.pull_request.number}}
  cancel-in-progress: true
jobs:
  e2e-tests-local-before-merge-to-testnet:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./e2e
    steps:
      - name: checkout JsWallet
        uses: actions/checkout@v2

      - name: get branch name
        run: echo ${{github.event.pull_request.head.ref}} && echo '::set-output name=branch_name::${{github.event.pull_request.head.ref}}'
        id: get-branch-name

      - name: checkout web3t, testnet branch
        uses: actions/checkout@v2
        with:
          repository: velas/web3t
          path: .compiled-ssr/web3t
          ref: testnet

      - name: try to checkout web3t, the same branch as JsWallet
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          repository: velas/web3t
          path: .compiled-ssr/web3t
          ref: ${{ steps.get-branch-name.outputs.branch_name }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: install latest npm
        run: npm install -g npm@latest

      - name: get node version
        run: node -v
      - name: get npm version
        run: npm -v

      # - uses: joschi/setup-jdk@v2
      #   with:
      #     java-version: '8'

      - name: install web3t modules
        working-directory: .compiled-ssr/web3t
        run: npm i

      - name: install lsxc
        run: npm i lsxc -g --unsafe-perm

      - name: copy web3 side by side to wallet
        working-directory: ../
        run: rm -rf JsWallet/.compiled-ssr/web3t/.git/objects/ && mkdir -p web3t/ && cp -pr JsWallet/.compiled-ssr/web3t/ ./

      - name: install wallet modules
        working-directory: ./
        run: npm i

      - name: delete wallet build cache
        working-directory: ./
        run: rm -rf ./.compiled

      - name: run wallet
        working-directory: ./
        run: |
          npm run wallet-start:no-watch &
          echo '- - - - - Wallet is started but it takes up to 30 seconds to be up - - - - -'

      - name: install test npm modules
        run: npm i

      - name: check token providers in default.conf
        working-directory: ./
        run: npm run test:check-token-providers-in-default-conf

      # - name: balances api health check
      #   run: CI=true npm run balances-api-health-check

      # - name: balances api health check
      #   run: CI=true npm run balances-api-health-check

      - name: check that wallet has started
        run: curl 127.0.0.1:8080 || (echo "ERROR! Walet has not started! Please check previous command output ^" && exit 1)

      - name: clean previous test report
        run: rm -rf ./test-report/

      - name: run tests
        run: CI=true npm test

      - name: upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: |
            e2e/test-report/
            e2e/test-report-swap/
          retention-days: 7

      # - name: deploy report to Github pages
      #   if: always()
      #   uses: peaceiris/actions-gh-pages@v2
      #   env:
      #     PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     PUBLISH_BRANCH: gh-pages
      #     PUBLISH_DIR: allure-history

      # - name: post the link to the report
      #   if: always()
      #   uses: Sibz/github-status-action@v1
      #   with:
      #       authToken: ${{secrets.GITHUB_TOKEN}}
      #       context: 'Test report'
      #       state: 'success'
      #       sha: ${{ github.event.pull_request.head.sha }}
      #       target_url: https://velas.github.io/JsWallet/${{ github.run_number }}
